# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXhxWBDv07v2NYiKWaBPJHRHYjT6S5w-
"""
import math
import random
import pickle
import os
import time

class TicTacToeAI:
    def __init__(self):
        self.board = [' '] * 9
        self.q_table = {}
        self.epsilon = 0.1 # تقليل العشوائية لزيادة التركيز على ما تعلمه
        self.alpha = 0.7   # زيادة سرعة التعلم
        self.gamma = 0.95
        self.load_q_table()
        
        self.nodes_evaluated = 0
        self.response_time = 0.0

    def check_winner(self, board, player):
        win_conditions = [[0,1,2], [3,4,5], [6,7,8], [0,3,6], [1,4,7], [2,5,8], [0,4,8], [2,4,6]]
        return any(all(board[i] == player for i in cond) for cond in win_conditions)

    def is_draw(self, board):
        return ' ' not in board and not self.check_winner(board, 'X') and not self.check_winner(board, 'O')

    def get_empty_squares(self, board):
        return [i for i, x in enumerate(board) if x == ' ']

    def make_move(self, square, player):
        if self.board[square] == ' ':
            self.board[square] = player
            return True
        return False

    def minimax(self, board, depth, is_maximizing, alpha, beta, ai_sym, player_sym):
        self.nodes_evaluated += 1
        if self.check_winner(board, ai_sym): return 10 - depth
        if self.check_winner(board, player_sym): return depth - 10
        if self.is_draw(board): return 0

        if is_maximizing:
            best_score = -math.inf
            for i in self.get_empty_squares(board):
                board[i] = ai_sym
                score = self.minimax(board, depth + 1, False, alpha, beta, ai_sym, player_sym)
                board[i] = ' '
                best_score = max(score, best_score)
                alpha = max(alpha, score)
                if beta <= alpha: break
            return best_score
        else:
            best_score = math.inf
            for i in self.get_empty_squares(board):
                board[i] = player_sym
                score = self.minimax(board, depth + 1, True, alpha, beta, ai_sym, player_sym)
                board[i] = ' '
                best_score = min(score, best_score)
                beta = min(beta, score)
                if beta <= alpha: break
            return best_score

    def get_best_move(self, mode, ai_sym, player_sym):
        start_time = time.perf_counter()
        self.nodes_evaluated = 0
        move = -1

        if mode == "Impossible (Minimax)":
            best_score = -math.inf
            for i in self.get_empty_squares(self.board):
                self.board[i] = ai_sym
                score = self.minimax(self.board, 0, False, -math.inf, math.inf, ai_sym, player_sym)
                self.board[i] = ' '
                if score > best_score:
                    best_score = score
                    move = i
        elif mode == "Learning (Q-Learning)":
            state = "".join(self.board)
            empty = self.get_empty_squares(self.board)
            if state not in self.q_table:
                self.q_table[state] = {m: 0.0 for m in empty}
            
            # استغلال الخبرة أو الاستكشاف
            if random.uniform(0, 1) < self.epsilon:
                move = random.choice(empty)
            else:
                move = max(self.q_table[state], key=self.q_table[state].get)
        else:
            move = random.choice(self.get_empty_squares(self.board))

        self.response_time = (time.perf_counter() - start_time) * 1000
        return move

    def train(self, state, action, reward):
        if state not in self.q_table:
            self.q_table[state] = {m: 0.0 for m in self.get_empty_squares(list(state))}
        current_q = self.q_table[state].get(action, 0.0)
        # تحديث فوري وبقوة (Bellman Equation simplified)
        self.q_table[state][action] += self.alpha * (reward - current_q)
        self.save_q_table()

    def auto_train(self, iterations=5000):
        for _ in range(iterations):
            temp_board = [' '] * 9
            history = []
            turn = 'X'
            while True:
                empty = [i for i, x in enumerate(temp_board) if x == ' ']
                if not empty: break
                state = "".join(temp_board)
                if state not in self.q_table: self.q_table[state] = {m: 0.0 for m in empty}
                action = max(self.q_table[state], key=self.q_table[state].get) if random.random() > 0.1 else random.choice(empty)
                temp_board[action] = turn
                history.append((state, action, turn))
                if self.check_winner(temp_board, turn):
                    self._backpropagate(history, 15, turn)
                    break
                elif ' ' not in temp_board:
                    self._backpropagate(history, 5, None)
                    break
                turn = 'O' if turn == 'X' else 'X'
        self.save_q_table()

    def _backpropagate(self, history, final_reward, winning_turn):
        for state, action, turn in reversed(history):
            reward = final_reward if turn == winning_turn else -final_reward if winning_turn else final_reward/2
            self.train(state, action, reward)
            final_reward *= self.gamma

    def save_q_table(self):
        with open('q_table.pkl', 'wb') as f: pickle.dump(self.q_table, f)

    def load_q_table(self):
        if os.path.exists('q_table.pkl'):
            with open('q_table.pkl', 'rb') as f: self.q_table = pickle.load(f)