# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TkhXobtVSrKWVbGvlsNgTZ7XlK7LxWbw
"""



import cv2
import mediapipe as mp
import math
 
class HandTracker:
    def __init__(self, min_detection_confidence=0.75, min_tracking_confidence=0.75):
        # 1. تهيئة مكتبة MediaPipe
        self.mp_hands = mp.solutions.hands
        self.hands = self.mp_hands.Hands(
            static_image_mode=False,
            max_num_hands=1, # إحنا محتاجين إيد واحدة بس تلعب
            min_detection_confidence=min_detection_confidence,
            min_tracking_confidence=min_tracking_confidence
        )
        self.mp_draw = mp.solutions.drawing_utils

    # 2. دالة معالجة الصورة (الفريم) اللي جاية من الكاميرا
    def process_frame(self, frame):
        # MediaPipe بيحب الألوان بصيغة RGB، و OpenCV بيقرأ بصيغة BGR
        img_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = self.hands.process(img_rgb)

        index_finger_pos = None
        is_clicked = False

        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                # رسم الهيكل العظمي للإيد على الصورة
                self.mp_draw.draw_landmarks(frame, hand_landmarks, self.mp_hands.HAND_CONNECTIONS)

                # استخراج أبعاد الصورة الحقيقية
                h, w, c = frame.shape

                # إحداثيات السبابة (رقم 8 في MediaPipe) والإبهام (رقم 4)
                index_tip = hand_landmarks.landmark[8]
                thumb_tip = hand_landmarks.landmark[4]

                # تحويل الإحداثيات النسبية لبيكسلات حقيقية
                ix, iy = int(index_tip.x * w), int(index_tip.y * h)
                tx, ty = int(thumb_tip.x * w), int(thumb_tip.y * h)

                index_finger_pos = (ix, iy)

                # 3. اكتشاف الـ Click (حساب المسافة بين السبابة والإبهام)
                distance = math.hypot(tx - ix, ty - iy)

                # لو المسافة أقل من 40 بيكسل، نعتبرها نقرة (Click)
                if distance < 40:
                    is_clicked = True
                    # رسم دائرة خضراء عشان اللاعب يتأكد إنه داس
                    cv2.circle(frame, (ix, iy), 15, (0, 255, 0), cv2.FILLED)
                else:
                    # رسم دائرة حمراء طول ما هو بيتحرك من غير ما يدوس
                    cv2.circle(frame, (ix, iy), 15, (0, 0, 255), cv2.FILLED)

        return frame, index_finger_pos, is_clicked

    # 4. دالة تحويل مكان الصباع لرقم المربع في اللعبة (من 0 لـ 8)
    def get_grid_position(self, x, y, frame_width, frame_height):
        # تقسيم الشاشة لـ 3 أثلاث بالطول والعرض
        col = x // (frame_width // 3)
        row = y // (frame_height // 3)

        # التأكد إننا مش بره الشاشة
        if col > 2: col = 2
        if row > 2: row = 2

        # تحويل الصف والعمود لرقم من 0 لـ 8 (زي الـ Board اللي في الـ AI)
        square_index = row * 3 + col
        return square_index

    # 5. رسم خطوط شبكة X-O على الشاشة عشان اللاعب يشوفها
    def draw_grid(self, frame):
        h, w, _ = frame.shape
        # خطوط أفقية
        cv2.line(frame, (0, h // 3), (w, h // 3), (255, 255, 255), 2)
        cv2.line(frame, (0, 2 * h // 3), (w, 2 * h // 3), (255, 255, 255), 2)
        # خطوط رأسية
        cv2.line(frame, (w // 3, 0), (w // 3, h), (255, 255, 255), 2)
        cv2.line(frame, (2 * w // 3, 0), (2 * w // 3, h), (255, 255, 255), 2)
        return frame

